name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - "backend/**" # Opcional: Dispara apenas se houver mudanças na pasta backend
      - "events/**" # Opcional: Dispara apenas se houver mudanças na pasta events

jobs:
  deploy-to-render:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Copiar pasta de eventos para o backend
        run: |
          mkdir -p backend/data_events # Garante que a pasta data_events existe
          cp -r ./events/* ./backend/data_events/ # Copia recursivamente o conteúdo de events para data_events

      - name: Deploy para Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
