name: Deploy Backend to Vercel

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Copy events to backend
        run: cp -r ./events ./backend/data

      - name: Install Dependencies
        run: npm install --prefix ./backend

      - name: Build Project Artifacts
        run: npm run build --prefix ./backend

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd ./backend

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --yes --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./backend
